import type { ComponentType, SVGProps } from 'react'
import {
  Search,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Calendar as LCalendar,
  Plus,
  ArrowUp,
  ArrowDown,
  Bell,
  HelpCircle,
  Settings as LSettings,
  Sparkles,
  LayoutDashboard,
  Users,
  ClipboardList,
  Upload,
  Phone,
  MessageSquare,
  SlidersHorizontal,
  Menu,
  Mic,
  X,
  History as LHistory,
  CheckSquare,
  DollarSign,
  Baby,
  MoreHorizontal,
  Info,
  FileText,
  Monitor,
  Eye,
  LayoutGrid,
  List as LList,
  AlertTriangle,
  Heart,
  TrendingUp,
  Stethoscope,
} from 'lucide-react'

type Props = SVGProps<SVGSVGElement> & { size?: number | string }

// Wrap a lucide icon so callers can pass `width`/`height` (our existing API)
// instead of `size`. Defaults match the prior visual weight.
const wrap = (Cmp: ComponentType<any>) => {
  return ({ width, height, size, strokeWidth = 1.8, ...rest }: Props) => {
    const resolved = size ?? width ?? height ?? 18
    return <Cmp size={resolved} strokeWidth={strokeWidth} {...rest} />
  }
}

export const Icon = {
  Search: wrap(Search),
  ChevronDown: wrap(ChevronDown),
  ChevronLeft: wrap(ChevronLeft),
  ChevronRight: wrap(ChevronRight),
  Calendar: wrap(LCalendar),
  Plus: wrap(Plus),
  ArrowUp: wrap(ArrowUp),
  ArrowDown: wrap(ArrowDown),
  Bell: wrap(Bell),
  Help: wrap(HelpCircle),
  Settings: wrap(LSettings),
  Sparkle: wrap(Sparkles),
  Tooth: wrap(Stethoscope),
  Dashboard: wrap(LayoutDashboard),
  Users: wrap(Users),
  Clipboard: wrap(ClipboardList),
  Upload: wrap(Upload),
  Phone: wrap(Phone),
  Chat: wrap(MessageSquare),
  Filter: wrap(SlidersHorizontal),
  Menu: wrap(Menu),
  Mic: wrap(Mic),
  Close: wrap(X),
  History: wrap(LHistory),
  CheckSquare: wrap(CheckSquare),
  Dollar: wrap(DollarSign),
  Child: wrap(Baby),
  Dots: wrap(MoreHorizontal),
  Info: wrap(Info),
  Notes: wrap(FileText),
  Monitor: wrap(Monitor),
  Eye: wrap(Eye),
  Grid: wrap(LayoutGrid),
  List: wrap(LList),
  Warn: wrap(AlertTriangle),
  Heart: wrap(Heart),
  TrendingUp: wrap(TrendingUp),
}
